# Generated by Django 2.2.4 on 2020-01-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pic',
        ),
    ]
