# Generated by Django 3.0.2 on 2020-01-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_answer_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
