# Generated by Django 3.0.2 on 2020-01-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_answer_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(),
        ),
    ]
